# Generated by Django 6.0.2 on 2026-03-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_tumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tumbnail',
            new_name='thumbnail',
        ),
    ]
